language: go
dist: focal
go:
  - '1.11.x'
  - '1.12.x'
  - '1.13.x'
  - '1.14.x'
  - '1.15.x'
  - 'tip'
jobs:
  include:
    - os: windows
      script:
      - go build
      - bash ./test.sh
    - os: osx
      script:
      - go build
      - ./test.sh
    - os: linux
      script:
      - go build
      - ./test.sh
